"""empty message

Revision ID: 583fb8a9af8c
Revises: 224028ed335e
Create Date: 2025-12-22 19:49:08.070855

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "583fb8a9af8c"
down_revision: Union[str, Sequence[str], None] = "224028ed335e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "specialists",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("speciality", sa.String(length=50), nullable=True),
        sa.Column("invoke_token", sa.String(), nullable=True),
        sa.Column("is_admin", sa.Boolean(), nullable=False),
        sa.Column(
            "specialist_status",
            sa.Enum(
                "ACTIVE",
                "ON_VACATION",
                "SICK_LEAVE",
                "INACTIVE",
                name="specialiststatus",
            ),
            nullable=False,
        ),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_specialists_id"), "specialists", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_specialists_id"), table_name="specialists")
    op.drop_table("specialists")
    op.drop_enum("specialiststatus", schema="public")
    # ### end Alembic commands ###
